spring:
  application:
    name: eventory-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/eventory}
    username: ${DATABASE_USERNAME:eventory}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    com.eventory: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always